/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_edd;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio
 */
public class VerUsuario extends javax.swing.JFrame {

    MetodosExtra metodo = new MetodosExtra();
    ImageIcon Mega = new ImageIcon("Mauri.png");
    static Usuario usuario;
    public void seleccionarUsuario(Usuario usuario){
        this.usuario=usuario;
    }
    /**
     * Creates new form UP
     */
    public VerUsuario(Usuario usuario) {
        this.usuario=usuario;
        initComponents();
        LabelImagen.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        btnTwitter = new javax.swing.JButton();
        btnSteam = new javax.swing.JButton();
        btnPSN = new javax.swing.JButton();
        btnNintendo = new javax.swing.JButton();
        LabelImagen = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        LabelDescripcion = new javax.swing.JLabel();
        LabelD = new javax.swing.JLabel();
        LabelNombreR = new javax.swing.JLabel();
        labelHoras = new javax.swing.JLabel();
        labelNoJuegos = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfil de "+usuario.getsApodo());
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);

        btnTwitter.setText("Twitter");
        btnTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwitterActionPerformed(evt);
            }
        });

        btnSteam.setText("Steam");
        btnSteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSteamActionPerformed(evt);
            }
        });

        btnPSN.setText("PSN");
        btnPSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPSNActionPerformed(evt);
            }
        });

        btnNintendo.setText("Nintendo");
        btnNintendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNintendoActionPerformed(evt);
            }
        });

        LabelImagen.setIcon(Mega);
        LabelImagen.setText("Imagen");

        LabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelUsuario.setText(usuario.getsApodo());

        LabelDescripcion.setBackground(new java.awt.Color(0, 51, 255));
        LabelDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescripcion.setText(usuario.getsDescripcion());

        LabelD.setText("Descripción de jugador:");

        LabelNombreR.setText(usuario.getsNombre());

        labelHoras.setText("Cantidad de horas jugadas: "+usuario.getiHoraxjuego());

        labelNoJuegos.setText("Numero de juegos: "+ usuario.getiNoJuegos());

        btnSalir.setText("Terminar de ver");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNoJuegos)
                    .addComponent(LabelD)
                    .addComponent(labelHoras)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTwitter)
                                .addGap(2, 2, 2)
                                .addComponent(btnSteam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPSN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNintendo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(287, 287, 287)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelUsuario)
                                    .addComponent(LabelNombreR))))
                        .addComponent(LabelDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelNombreR))
                    .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelNoJuegos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTwitter)
                    .addComponent(btnSteam)
                    .addComponent(btnPSN)
                    .addComponent(btnNintendo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(LabelD)
                .addGap(18, 18, 18)
                .addComponent(LabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwitterActionPerformed
    metodo.enlace(usuario.getsTwitter());        
    }//GEN-LAST:event_btnTwitterActionPerformed

    private void btnSteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSteamActionPerformed
    metodo.enlace(usuario.getsSteam());
    }//GEN-LAST:event_btnSteamActionPerformed

    private void btnPSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPSNActionPerformed
        JOptionPane.showMessageDialog(jMenu1, "PSN ID:\n"+usuario.getsPSN(), "PSN ID", WIDTH);
    }//GEN-LAST:event_btnPSNActionPerformed

    private void btnNintendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNintendoActionPerformed
        JOptionPane.showMessageDialog(jMenu1, "Código de amigo Nintendo Switch: \n"+usuario.getsNSFCode(), "Nintendo Switch Friend Code:", WIDTH);
    }//GEN-LAST:event_btnNintendoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        
        hide();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerUsuario(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelD;
    private javax.swing.JLabel LabelDescripcion;
    private javax.swing.JLabel LabelImagen;
    private javax.swing.JLabel LabelNombreR;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JButton btnNintendo;
    private javax.swing.JButton btnPSN;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSteam;
    private javax.swing.JButton btnTwitter;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JLabel labelHoras;
    private javax.swing.JLabel labelNoJuegos;
    // End of variables declaration//GEN-END:variables
}
